
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    url: jdbc:mysql://rm-2ze2b843joe3i0e3ouo.mysql.rds.aliyuncs.com:3306/institution?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: qa
    password: Gaosi2019
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true
  slave1:
    url: jdbc:mysql://127.0.0.1:3306/institution?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true

  slave2:
    url: jdbc:mysql://60.205.217.5:3306/institution?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: qa
    password: Gaosi2019
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true
